@startuml
actor 会員 as a 
participant "：商品検索画面" as b <<boundary>>
participant "：商品検索コントローラ" as c <<control>>
participant "：商品" as d <<entity>>
participant "：商品カテゴリ" as e <<entity>>
activate a
a -> b :商品検索（商品番号）
activate b
b -> c :商品検索（商品番号）
activate c
create d
c -->> d :<<create>>生成（）
loop 商品カテゴリ
create e
c -->> e :<<create>>生成（） 
c -> d :商品カテゴリ設定
activate d
deactivate d
end loop
b <-- c :商品情報
deactivate c
b -> b :商品情報開示（商品情報）
activate b

@enduml