@startuml 
object "Aさん:利用者クラス" as Aさん{

}
object "Bさん:利用者クラス" as Bさん{

}
object "301号室:部屋クラス" as 301号室{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}
object "302号室:部屋クラス" as 302号室{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}
object "303号室:部屋クラス" as 303号室{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}
Aさん--301号室
Bさん--303号室
@enduml