@startuml 
object "髙橋洋平さん:重要顧客クラス" as 髙橋洋平さん{

}
object "高田利恵さん:顧客クラス" as 高田利恵さん{

}
object "大坪直之さん:顧客クラス" as 大坪直之さん{

}
object "テレビ:商品クラス" as テレビ{
    商品名=テレビ
    型式=V12345
}
object "冷蔵庫:商品クラス" as 冷蔵庫{
    商品名=冷蔵庫
    型式=R8765
}
object "プロジェクタ:商品クラス" as プロジェクタ{
    商品名=プロジェクタ
    型式=P1122
}
object "注文1:注文クラス" as 注文1{
    注文日=11月21日
    数量=2
} 
object "注文2:注文クラス" as 注文2{
    注文日=11月21日
    数量=1
} 
object "注文3:注文クラス" as 注文3{
    注文日=12月23日
    数量=1
} 
髙橋洋平さん -- 注文1
注文1 -- テレビ
髙橋洋平さん -- 注文2
注文2 -- 冷蔵庫
高田利恵さん -- 注文3
注文3--冷蔵庫
@enduml