@startuml

  |顧客|
  |顧客|
  |スタッフ|
  |スタッフ|
  |厨房|
  |厨房|
  |スタッフ|

  start
  :挨拶をかます;
  :注文を聞く;
  |スタッフ|
  |顧客|
  :注文せざるを得ない;
  |顧客|
  |スタッフ|
  :注文を確認する;

  fork
    :代金を請求;
    |顧客|
    :しゃーなし代金を支払う;
    |顧客|
    |スタッフ|
    :清算ッ！;
    |スタッフ|

  fork again
    :商品の調理を依頼する;
    |厨房|
    :商品を料理する;
    |厨房|
  |スタッフ|

  end fork
  |スタッフ|
  :テイクアウトか尋ねる;
  if () then (テイクアウト)
    :袋に挿入;

  else (店内)
    :トイレにのせる;

  endif
  :商品を渡す;
  |スタッフ|
  |顧客|
  :商品もらう;
  |顧客|
  stop
@enduml